version: "3.9"
services:
  api:
    build: ./backend
    container_name:   dijital-ayak-izi-api
    ports:
      - "8005:8000"
    environment:
      - ENV=dev
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  ui:
    build: ./frontend
    container_name: dijital-ayak-izi-ui
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

